### PR TITLE
database: add user

### PR DESCRIPTION
**Pull request by Ddan-X**

### CODE REVIEW

**Review by andykawabata — APPROVED** [review]
Looks good thanks! In the future, you might want to change the underscores to camel case. Just so we have consistency in our code. like u_name should be uName.

**Review by mcleoar — APPROVED** [review]
Looks good on my end. I can wait and see it run at our next meeting.

**Review by jfwillia — COMMENTED** [review]
As @andykawabata mentioned, using camelCase would make this more consistent with the rest of the code.

**Review by jfwillia — COMMENTED** [review]
You shouldn't put default credentials in your repo code.  Instead, you can leave url, username, and password blank, put a note in the README.md that these values need to be configured prior to running.

**Pull request merged**
